### ISSUE TITLE
More Defined Parts List in Readme

### ISSUE THREAD

**Issue by IRobL** [xtensa/PodEmu#6]
Hi, great work on this code base, it really stands to improve a lot of ppls lives.  

After a quick look in the readme, I couldn't figure out what parts were necessary.  I also couldn't figure out where to get PodDock at all (Edit: I just found this after closing some tabs acutally... APPLE-30M-BO-V1AC)!  The closest alternative I could find was the part with the searchable ID `APPLE-30M-BO-V1AV` but it isn't an 'in-line' style device, it's more like a part you would use when building an actual dock :(  Any ideas as to where to find this, and does adding a section to the readme including parts sound like a good idea?  e.g.

### Parts List (Blue Tooth Build)
- Bluetooth (Radio?) Supporting SPP (HC-05, RN52, etc.)
- Bluetooth Serial Interface (FT232R, FT231X, FT311D, FT312D, PL2303, CP2102, CP2105, CP2108 or CP2110)
- Bluetooth Audio Streaming thing (XS3868)
- 1amp DC-DC step down converter (LM2596)
- Apple 30pin breakout (APPLE-30M-BO-V1AC)

### Parts List (Direct Connect Build)
- Serial Interface (FT311D or FT312D)
- 1amp DC-DC step down converter (LM2596)
- Apple 30pin breakout (APPLE-30M-BO-V1AC)
- Another thing??

**Comment by xtensa** [comment]
Thanks for suggestion. I added "Hardware" section that I believe should clarify things a little. Also, in the description above you mixed things up, because for direct connection you don't need to use usb-to-serial adapters and in direct connection build you missed them. 

Additionally, the aim of this project is not to instruct where to buy components. I know that PodSocket is hardly available but you can always buy any cheap iPod adapter and disassemble it.

**Comment by IRobL** [comment]
Thank you for adding that detail section, it's sure to help as I get moving on this project!  

Also as a note, in case anyone reviews this thread looking for what part numbers can be used to expose the car's IPod pins to convienient soldering, the 30M part I had originally listed won't work, you'd want one listed as 30F for female.

**Comment by xtensa** [comment]
Yes, it should be female port as in iPod, not in the cable. Yes, they are
hardly available, but it is possible to find some. There was informacion on
project XDA thread.

**Comment by ArranDev** [comment]
I did want to put this on XDA but their registration system seems to not be working. Even though this issue is closed and somewhat old I think the following fits in well and that it would be useful/helpful.

Since some of the parts are a bit difficult to find (particularly a 30 pin breakout board that doesn't involve breaking apart a 30 pin to lightning adapter) I thought it may be helpful/useful to actually put together a list of components to make the cable. I've stuck to only using Amazon and eBay (just because they have good return policies/buyer protection). The only thing I haven't included is solder and a soldering iron.

The schematics I'm following for the list are the one for the cable (not the Bluetooth versions as they're more complicated): https://raw.githubusercontent.com/xtensa/PodEmu/master/schematics/PodEmu%20Wired.png

**Just a disclaimer**, I haven't made a cable and I also don't have an iPod dock or car with an infotainment system that uses the 30-pin iPod connector for music (at this moment in this is). I also don't know 100% if these parts do work together or if (especially the 30-pin breakout board and USB Serial are the correct parts). Please do correct me if this is wrong.


- **Apple 30-pin breakout board**
30-pin Female breakout board (the shipping seems quite pricy): https://ebay.us/zlFqiD
_As mentioned you could butcher a 30 pin to lighting adapter but I wanted to avoid this in the list._
~~Male 30-pin breakout board (the shipping seems quite pricy): https://ebay.us/yUshr3~~
_The above was a male 30-pin and not a female 30-pin._

- **USB Serial**
CP2102: https://www.amazon.co.uk/UART-CP2102-Module-Serial-Converter/dp/B00AFRXKFU/
OR
PL2303: https://www.ebay.co.uk/itm/PL2303-TA-USB-to-TTL-RS232-Serial-Adapter/283657053343

- **3.5mm aux** (few potential choices/ways you can go about this)
3.5mm aux jack (male): https://www.amazon.co.uk/Terminal-Connector-Ancable-Soldless-Headphone/dp/B07MDJ61Z8/
_This would need you to wire the 3.5mm aux jack to your 30 pin breakout board_
OR
3.5mm aux jack cable to bare wire (male): https://www.amazon.co.uk/Ancable-1-Pack-Shielded-Speaker-Headphone-Stereo/dp/B07S599GQK/
_This would be if you wanted to directly wire the 3.5mm jack directly to the 30 pin breakout board without needing to sort your own wires out (like jack above)._
OR
3.5mm aux jack (female): https://www.amazon.co.uk/Adafruit-Breadboard-Friendly-Stereo-Headphone/dp/B00OKCRBNI
_This does deviate from the schematic somewhat but using something like this instead would allow you to use your own aux cable that you plugged into the 'PodEmu Cable'_


- **Resistor (470 ohms)**: https://www.amazon.co.uk/Projects-100EP514470Ruk-470-Resistors-Pack/dp/B07YN73RNT/
_This does have multiple resistors in a pack since you can't really just buy a single resistor on its own_

- **Diode**: https://www.amazon.co.uk/50-1N4148-Signal-Switching-Diode/dp/B00XWE2SYM
_Just like the resistor, this has multiple diodes in a pack since you can't really just buy a single diode_

- **For wiring everything up**
On amazon prime: https://www.amazon.co.uk/Solderless-Flexible-Breadboard-different-lengths/dp/B01LXTI2E3/
OR
Non-prime but cheaper (or at least at the time cheaper): https://www.amazon.co.uk/Solderless-Flexible-Breadboard-Jumper-Arduino/dp/B00GX6V48C/

**Comment by padraigfl** [comment]
Sorry to be posting on a closed issue from so long ago, not sure where the best spot to share this would be.

The 30 pin bluetooth adapters that you can get reasonably cheaply (as low as $3 delivered) look like they are currently the best low cost option for this project and similar projects. I haven't actually gotten around to seeing if it would work but I would assume the traces involved directly correspond with the pins used from the podsocket PCB?

Here are some photos of what the board looks like:

![Image](https://github.com/user-attachments/assets/94f81fa6-efd1-4a7a-8740-ff9aa8472a20)
![Image](https://github.com/user-attachments/assets/46c0def0-b119-43ef-bda3-d860b7ebdec5)
![Image](https://github.com/user-attachments/assets/792a2da5-a44e-47b4-887a-a5baa176f9c6)

If you'd like some higher res photos I can send some on.
