### ISSUE TITLE
Podemu crashing since last update (3.0-53)

### ISSUE THREAD

**Issue by Yosemite73** [xtensa/PodEmu#7]
Hi,
Since the last update, PodEmu keeps crashing everytime I open my Stingray music application and crashes non-stop until I close Stingray (BTW its a music app provided by my ISP.
[PodEmu_debug.txt](https://github.com/xtensa/PodEmu/files/2660000/PodEmu_debug.txt)
![screenshot_20181208-143246_stingray music](https://user-images.githubusercontent.com/45720046/49689938-cf342500-faf6-11e8-8630-30372618e5a9.jpg)
![screenshot_20181208-143437_device maintenance](https://user-images.githubusercontent.com/45720046/49689939-cf342500-faf6-11e8-819c-c82d06a8139b.jpg)

**Comment by xtensa** [comment]
Thanks for reporting the issue. I'll try to fix it ASAP, but you need to
collect better logs. The one you attached is less then one minute long and
does not contain "crash" event.

**Comment by xtensa** [comment]
Yosemite73, please test it with version 3.0-57 which I uploaded to the Market and let me know if the problem still exists.

**Comment by Yosemite73** [comment]
Can't find the 3.0-58 APK file, can you e-mail it to me plz? And as for the log, I kept it short so hopefully you could find the problem faster, the logging was enabled when the app crashed. fortier73@hotmail.com

**Comment by Yosemite73** [comment]
Never mind the APK, updated it from play store... Unfortunately, still crashes every time I start up Stingray.

**Comment by xtensa** [comment]
Can you please install this version of app and collect the logs again please?
[app-release.apk.zip](https://github.com/xtensa/PodEmu/files/2660828/app-release.apk.zip)
This version does not solve the problem, I only enabled better logging to understand the problem. Unfortunately I cannot test the application with Stingray Music myself, because it is not available for EU citizens. As I understood it is available only in US and Canada. So I need your help to track down the issue.

**Comment by Yosemite73** [comment]
Well for some reason version 3.0-59 works fine, Podemu is stable. So I reinstalled version 3.0-58 to try it again and the problem came back...
[PodEmu_debug.txt](https://github.com/xtensa/PodEmu/files/2660928/PodEmu_debug.txt)

**Comment by xtensa** [comment]
Actually I needed log from version 59 specifically, because version 58 does not log full information about the crash. Anyway, because you didn't erase debug log after downgrading to 58, logfile contained what I needed from 59, so I was able (i think so) to fix the issue properly :) . Version 59 contained just dirty workaround, but it worked.

To make sure all is fixed correctly now, can you please install this version (60), collect logs for ~1 minute of using PodEmu and upload it please?
[app-release-3.0-60.apk.zip](https://github.com/xtensa/PodEmu/files/2660970/app-release-3.0-60.apk.zip)

**Comment by Yosemite73** [comment]
Here's a new log with version 3.0-60, if you need any more let me know!
[PodEmu_debug.zip](https://github.com/xtensa/PodEmu/files/2664252/PodEmu_debug.zip)

**Comment by xtensa** [comment]
Everything looks good in the log, so I am closing the issue. Thanks for helping me to solve this problem.

Updated app is already rolled out to Google Play Store (version 61).
