### ISSUE TITLE
Feature Request: Bovee 1000 Bluetooth

### ISSUE THREAD

**Issue by PaulMz02** [xtensa/PodEmu#9]
Is it possible for PodEmu to work over the Bovee 1000 bluetooth to 30pin interface? Without PodEmu, the Bovee (aka ViseeO tune2air) only plays the music and all control is done over the phone. No metadata is transmitted and the device controls don't work.

https://www.amazon.com/Bovee-Wireless-Bluetooth-Interface-Integration/dp/B00B52LLJ6.

If a test unit is needed, PM me and one can be provided.

**Comment by xtensa** [comment]
Cannot answer straight away this question. Can you please install Bluetooth Devices Info app (https://play.google.com/store/apps/details?id=com.rockfort.bluetoothinfo) and upload the screenshot for Bovee 1000?

**Comment by PaulMz02** [comment]
Here you go!

**Comment by xtensa** [comment]
There is no attachment :( I guess you need to upload it directly on github.

**Comment by PaulMz02** [comment]
Second try

![screenshot_20190228-100613](https://user-images.githubusercontent.com/48094716/53576889-aabe7680-3b42-11e9-9cdb-e88b2f8ad8d0.png)

**Comment by PaulMz02** [comment]
Debug file from PodEmu trying to connect to Bovee. Scrubbed for email addresses.

[PodEmu_debug.txt](https://github.com/xtensa/PodEmu/files/2915643/PodEmu_debug.txt)

**Comment by xtensa** [comment]
PodEmu will not connect to Bovee because it does not provide SPP profile. Also it does not provide iAP (Apple profile) which is not supported by PodEmu but theoretically is possible to implement. I see that Bovee is using standard AVRCP profile to transfer all metadata and controls. And if you read comments here: https://www.viseeousa.com/collections/tune2air/products/viseeo-tune2air-wma1000-wireless-bluetooth-music-interface-adaptor-for-in-car-ipod-integration-30pin-ipod-connector for other users it works correctly with Android (only it will not shouw playlist, but this is obvious and it is Android limitation). So actually, there is no need to use it with PodEmu - it should work with Android and controls should also work.

**Comment by PaulMz02** [comment]
okay. I do have it working to that extent, but want the playlist functionality. Also, even though their website says so, the steering wheel controls don't work on my car.

Anyways. I can dust off my solder kit and DIY an adapter. It looks like I should do the RN52 schematic since I don't have PCB access.

Thank you for taking the time to look at this!

**Comment by xtensa** [comment]
But please be aware, that you will not have full playlist functionality with PodEmu either. There is no way to receive this information from media players so it cannot be provided to the car.

**Comment by PaulMz02** [comment]
That is ok. I would be happy with title/artist and pause/skip from the steering wheel.

That being said, it looks like the breakout boards are no longer available. This might be harder than I thought.

**Comment by qwertiger** [comment]
Hello all.
@xtensa , @PaulMz02 

To get this right: 
I was searching and reading regarding the Tune2air, let's say for a longer time and I found out the following things:
Tune2air has AVRCP protocol but most probably only the 1.0 AVRCP version. 1.0 version provides only basic "controls support" (e.g. play / stop, next track, previous track) commands. But for viewing the metadata it uses some different protocol. Therefore on Android devices it works only with the following functionality:
- A2DP music streaming
- basic controls over AVRCP 1.0 protocol
(this I tested by myself and it works - also the track skipping function). But metadata is not shown on Android (as we know there is needed at least AVRCP version 1.3 to show metadata on Android) but is shown on Apple devices because of some let's say "special Apple protocol".
On the manufacturer's page they are stating that it uses Airplay protocol (please search on the page for "Airplay"):
http://viseeo.net/products/bluetooth-audi/tune2air-wma1000/

But Airplay uses the Wi-Fi connection, not Bluetooth, and Tune2air clearly has a Bluetooth chip only. I've been searching a lot for "Airplay Bluetooth implementation" but I wasn't able to find anything, as Airplay over Bluetooth practically probably doesn't even exist (in any devices). Then I found out that Apple usually uses AAP or as you stated "iAP" protocol to communicate between Apple devices over Bluetooth / by cable. Finally, I ran over the BMW forum where they are discussing the implementation of their custom hardware over Bluetooth (in some ways similar to PodEmu project) but they wanted to implement everything inside the hardware (no need for an Android app as with PodEmu). But ok it doesn't matter for this Tune2air feature request. What matters is that on the mentioned forum they were discussing also the Tune2air adapter, and they are stating several times info about iAP protocol within Tune2air (please search for "iAP"):
https://forum.bmw5.co.uk/topic/81014-30-pin-bluetooth-dongle-with-avrcp-13-or-greater-for-id3-tag-support/?page=4

"Viseeo" or later rebranded "Bovee" company (Tune2air manufacturer) clearly is not one of the most supportive when it comes to answering customers' questions (and even while Firmware is upgradable for Tune2air devices, they probably won't implement AVRCP 1.3 or above firmware for Tune2air any soon). Moreover, on the above-mentioned forum, they also stated that there probably was a webpage from the company, where it was stated: "Supports Apple’s iAP over Bluetooth technology". This page unfortunately is not able to be opened anymore but it probably was there. 
So my conclusion:
Tune2air probably uses the iAP protocol, but this protocol is not usually used within Android Bluetooth devices. Therefore the "Bluetooth devices info app" above won't show this protocol in the list (because it probably simply doesn't recognize it).

Questions / Notes:
- Do you think it's possible in some way to implement iAP in PodEmu as then the metadata should be probably transferred from Android phone to Tune2air adapter? (I know that some car stereo manufacturers already implemented Android iAP functionality in their systems so e.g. iPhone is able to be connected to the car stereo unit and this car stereo unit uses Android and shows all metadata)
- Most of us Tune2air owners would be satisfied if only the function of showing the currently playing track info will work with Android (no need for browsing functionality)
- as a "bonus" I'm providing the link for one project where is used iPod controlled via Arduino over Bluetooth from an Android app (so the opposite direction implementation). Track info from iPod is shown within the Android app and there is also stated iAP protocol:
https://www.instructables.com/id/Hack-Your-Old-iPod-Device-Make-A-Bluetooth-Control/
Android app is called "MuseHack". It's not anymore on the Google play, but .apk can be found somewhere over the net (I think apkpure or so like page...)

**Comment by xtensa** [comment]
Dear **qwertiger**, thanks for the comments/questions, but they are not related to the original topic of this ticket, which is support for Bovee1000. Please kindly ask your questions on XDA forum, I will be glad to answer them.  Github should only be used for bug reporting or feature requests.

Short answer to your questions: PodEmu already implements iAP and I didn't understand what you need more. And there is no sth like "Android iAP".

**Comment by mirh** [comment]
*Ackchyually* bluez has included a super duper barebone IAP [skeleton](https://github.com/bluez/bluez/blob/master/profiles/iap/main.c) since version 5.1. 
And while it never went far and the official android repos even switched to bluedroid, I suppose it's not a technical impossibility.

Then [apparently](https://www.vwvortex.com/threads/android-mmi-for-pre-2013-vehicles-android-avrcp-and-tune2air.6010424/) the bovee just needed some update to be "workable" for android, but however good that may be I swear that even after 15 minutes of googling I couldn't find a single person (even recently) reporting non-iphones with functioning metadata. 
And so, yeah, I'm sure it has AVRCP.. but unless apple somehow extended the protocol to add some custom command, very fat chances are they are just using iAP for media info and whatnot. 

Therefore, last but not least, it is presumably in this sense that "PodEmu to work over the Bovee interface" kinda meant to use *wireless iAP* over bluetooth ~normally, rather than anything through the USB serial bridge (and of course the simple BT-USB adapter or [other](https://github.com/oandrew/ipod-gadget) [solutions](https://github.com/martinroger/ipodesp32) are smoother.. but if you already have the dongle at home I suppose it'd be a pity to throw it away?).
